name: bkapp_flutter
description: A new way for saving money in communities.

version: 1.0.2+4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bk_core:
    # path: /home/familia/projects/fundefir/bk_core
    git:
      url: git@github.com:Fundefir-dev/bk_core.git
      # ref: master
      ref: v0.3.0
  flutter_svg: ^0.18.0
  flutter_form_bloc: ^0.19.0
  form_bloc: ^0.19.0
  cupertino_icons: ^0.1.2
  animate_do: ^1.7.2
  http: ^0.12.2
  alice: ^0.1.3
  sqflite: ^1.3.1+1
  flutter_sqflite_manager: ^0.1.2
  path_provider: ^1.6.10
  mockito: ^4.1.1
  equatable: ^1.2.0
  logger: ^0.9.1
  sentry: ">=3.0.0 <4.0.0"
  flutter_contact: ^0.6.1
  easy_permission_validator: ^2.0.0
  intl: ^0.16.1
  mock_data: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  bloc_test: ^7.0.0
  remove_from_coverage: 1.0.7
  pin_code_fields: ^3.1.2
  flutter_launcher_icons: "^0.7.0"
  flutter_launcher_name: "^0.0.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 100
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 200
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_launcher_name:
  name: "Bk App (EN PRUEBAS)"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/splash.png"
  adaptive_icon_foreground: "assets/launcher/splash.png"
