on:
  push:
    branches:
      - master
name: Test, Build master
jobs:
  build:
    name: Run test on master
    runs-on: ubuntu-latest
    steps:
      - name: Configure git credentials
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://x-access-token:${{ secrets.ORG_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global url."https://github.com/".insteadof git@github.com:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ORG_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.5"
      - run: flutter pub get
      - run: flutter test --coverage && flutter pub run remove_from_coverage -f coverage/lcov.info -r 'lib/generated' -r 'lib/src/screens/homeTest'
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
  release-on-push:
    name: Generate a release github
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.FUNDEFIR_APT }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
