on: pull_request
name: Test PR
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - name: Configure git credentials
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://x-access-token:${{ secrets.ORG_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global url."https://github.com/".insteadof git@github.com:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ORG_TOKEN }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.5"
      - run: flutter pub get
      - run: |
          flutter test --coverage && \
          remove="flutter pub run remove_from_coverage -f coverage/lcov.info";for line in $(cat .coverage_exclude); do remove="$remove -r '$line' " ; done;echo $remove; eval $remove;
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
